To solve the "ImportError: always import a name 'LlamaTokenizer' from 'transformers. Models. Llama" problem (#745)
RuntimeError: Failed to import modelscope.models.nlp.llama2 because of the following error (look up to see its traceback):
*aot imoont mame 'lamalokenizer'from tnansformers.models,llama /e:PVthoPvthn311li site-Dackagesitransformers models llama init.y